#pragma once

namespace GameCore::Npc::Enemy::Tyrannosaurus
{
    // Animation indices in T-Rex.mv1; Take001 / Still are empty takes.
    enum class AnimationType : int
    {
        WalkSlowLoop         = 0,
        Take001              = 1,
        Still                = 2,
        Bite90Left           = 3,
        Bite90Right          = 4,
        BiteCloseLeft        = 5,
        BiteCloseRight       = 6,
        BiteStepBackForward  = 7,
        ChaseBiteLeft        = 8,
        ChaseBite            = 9,
        ChaseBiteRight       = 10,
        ChaseHeadButtLeft    = 11,
        ChaseRoarRight       = 12,
        ChaseRoarLeft        = 13,
        ChaseRoar            = 14,
        ClimbDown            = 15,
        ClimbUp              = 16,
        Death                = 17,
        DeathShort           = 18,
        HitHead1             = 19,
        HitHead2             = 20,
        HitHead3             = 21,
        HitLeg               = 22,
        HitLeg2              = 23,
        HitTorsoLeft         = 24,
        HitTorsoRight        = 25,
        HumanBite            = 26,
        HumanKill            = 27,
        HumanShake           = 28,
        IdleAttack           = 29,
        IdleAttackToRunLeft  = 30,
        IdleAttackToRunRight = 31,
        IdleInvestigate      = 32,
        IdleInvestigateLoop  = 33,
        IdleInvestigateOut   = 34,
        IdleSneeze           = 35,
        IdleToRun            = 36,
        LookForward          = 37,
        LookForward2         = 38,
        LookLeft             = 39,
        LookRight            = 40,
        MamaCaveBite         = 41,
        MamaCaveBiteLoop     = 42,
        MamaCaveBiteOut      = 43,
        RoarLeft             = 44,
        RoarRight            = 45,
        BigRoarStep          = 46,
        Roar                 = 47,
        RunHeadButtRight     = 48,
        RunToStop            = 49,
        HeadButtLeft         = 50,
        RunHeadLow           = 51,
        RunHeadLow2          = 52,
        WalkHeadLow          = 53,
        RunHeadLoop          = 54,
        WalkLoop             = 55,
        SprintHeadLeft       = 56,
        SprintHeadRight      = 57,
        SprintLoop           = 58,
        StepBack             = 59,
        LongDeath            = 60,
        Stunned              = 61,
        KillLong             = 62,
        Turn90Left           = 63,
        Turn90Right          = 64,
        Turn180Right         = 65,
        Turn180Look          = 66,
        Turn180TurnRight     = 67,
        WalkBack             = 68,
        WalkLeftBite         = 69,
        WalkRightBite        = 70,
        WalkBite             = 71,
    };
}
